language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
install:
- npm install
script: npm run build
after_success:
- bash .travis/push.sh
env:
  global:
    secure: cp1xkQWsh6W5HOBGtqJe5C5TCaj9LwRJIr8MtXVmZlrRdOF3zl8nnmVYVHZY9DTgrxc6N9qumX/JqYdXZrMRNDQWj9zjBLk5RviR8jY9FYtOnOp/7y+Fj195snYc6EGcCkBRJIhZYhXO3EFOlyNi0kWUDpFiXaOmyOTcfvW1iKzweGGQf1JJT8FOHD5XssL6LjpRA+GXr6ROoy6NpLJkzD05YAr2jr+76aiwHyo8PGJrkxl6+fFjD2oGUcsbcIMSLXA63yJQeFMsuimQdsyM9s0QXG5MC4cdaMoyOgiMAGbGZnOXr1kbcglQmDBiV1893/MC82NoY4MTB4DEzlKQUDJ5m4u7ydRPNeBL1ToSErsLkObKOTuqhdyduN64i+CXV+y269OKA+dq+qTOqgFvT50EyU4XqNNXN/akEsN1Doty08JwiFEGBbEpZVcOsDkES1D7bBVrtOoC8lEP7nNKgOu14Cjg38L7nimPiTImngh7s0bDVBsypq+SpIF0pk50xs0BB29SmMnmcR7K6jWrslJO2Iss7BndiWamkzGfRqz7Z1XOLHZiVonF6aHqaeei0foO4N3AEkpsboaIsPJM4KOGFCLP/lkAv68Qt3+o6lvArNOAG/oYoBB66HKH4dyCJ2be5ysXrwiyuvRqKDuaqn1C/r4G59HkwLPBJ9t0xlQ=
